name: CI-CD-Pipeline
env:
  S3_BUCKET_NAME: "github-actions-app"
  EB_APPLICATION_NAME: "simple-react-app"
  EB-ENVIRONMENT_NAME: "Simplereactapp-env"
  DEPLOY_PACKAGE_NAME: "github-actions-${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-west-2"
on:
  push:
    branches:
      - master
jobs:
  ci-part:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Upload ZIP package to S3 Bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.S3_BUCKET_NAME }}/